version: 1.2.{build}
branches:
  only:
  - tfs2013
configuration: Debug
build:
  verbosity: minimal
after_build:
- 7z a %APPVEYOR_PROJECT_NAME%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\*.dll
artifacts:
- path: '*.zip'