version: 1.2.{build}
branches:
  only:
  - tfs2013
configuration: Debug
environment:
  containerURL:
    secure: 5ScgXebma0ZLFaW1DPgEdqis7MzXvPJL+c1O+f+gfkzqwAEzVmhk6ZmISlcgxCL3XOLD5ID2nweLVV5CitmsDsC6PVlxsbfDFgmolBxKHg4=
  referenceFolder: References
install:
  # get all files from container
  - ps: $containerList = "$env:TEMP\references.xml"
  - ps: Invoke-RestMethod -Uri "$env:containerURL`?restype=container&comp=list" -OutFile $containerList
  - ps: $files = Select-Xml -XPath "//Name" -Path $containerList | foreach { $_.Node.InnerText }
  - ps: foreach ($file in $files) { Invoke-RestMethod -Uri "$env:containerURL/$file" -OutFile "$env:referenceFolder\$file" }
build:
  project: TFSAggregator.sln
  verbosity: minimal
after_build:
  - 7z a "%APPVEYOR_PROJECT_NAME%-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip" .\bin\%CONFIGURATION%\* -r -x!bin\%CONFIGURATION%\Microsoft.* -x!bin\%CONFIGURATION%\System.* -x!bin\%CONFIGURATION%\Newtonsoft.*
artifacts:
  - path: '*.zip'
